log:
  level: warning|info|fatail|critical|debug
github:
  user:
  default:
aws:
  region: eu-west-1
  access:
  secret:
consul:
  servers:
    MyNameServer:
      name: localhost
      port:
      protocol: http://
uptimerobot:
  token: