log:
  level: warning|info|fatail|critical|debug
github:
  user:
  default:
aws:
  region: eu-west-1
  access:
  secret:
consul:
  servers:
    MyNameServer: #(comment to delete) This name is display when agent is unreachable
      name: localhost|fqdn
      port: 8500
      protocol: http://
uptimerobot:
  token:
countdown:
  ie: 'Jul 26, 2015 00:00:00'
